version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      - run: npm run build

      - run:
          command: |
            tar cvf application.tar.gz -C build .
            mkdir -p /tmp/artifacts
            mv application.tar.gz /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    machine:
      enabled: true

    steps:
      - run:
          command: |
            mkdir -p temp-gh-pages
            cd temp-gh-pages

      - run:
          command: |
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1
            git init
            git remote add --fetch origin "$CIRCLE_REPOSITORY_URL"
            if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
            then
                git checkout gh-pages
                git rm -rf .
            else
                git checkout --orphan gh-pages
            fi

      - run:
          command: |
            curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN | grep -o 'https://[^"]*' | xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
            tar xvf application.tar.gz?circle-token=$CIRCLE_TOKEN .
            rm -f application.tar.gz*

      - run:
          command: |
            echo "chancethecoder.me" > CNAME

      - run:
          command: |
            git add -A
            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
            git push --force --quiet origin gh-pages

      - run:
          command: |
            cd .. && rm -rf temp-gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master