version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test

      - run: yarn build

      - run:
          command: |
            tar cvf application.tar.gz -C build .

      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv application.tar.gz /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "cc:13:50:8f:63:f3:2e:9c:3a:48:ef:21:dd:85:23:43"

      - run:
          command: |
            echo "Deploy Over SSH"
            ssh -v $SSH_USER@$SSH_HOST << EOF
              rm -f application.tar.gz*
              curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN | grep -o 'https://[^"]*' | xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
              pm2 delete all
              rm -rf playground/*
              tar xvf application.tar.gz?circle-token=$CIRCLE_TOKEN -C playground
              pm2 serve playground 3000
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master