version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test

      - run: yarn build

      - run:
          command: |
            tar cvf application.tar.gz -C build .

      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv application.tar.gz /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            echo "Deploy Over SSH"
            ssh SSH_USER@SSH_HOST << EOF
              url="https://circleci.com/api/v1.1/project/github/chancethecoder/playground/latest/artifacts?circle-token=$CIRCLE_TOKEN&branch=master"
              curl -s "$url" | grep -o 'https://[^"]*' | xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
              pm2 delete all
              rm -rf playground/*
              tar xvf application.tar.gz?circle-token=$CIRCLE_TOKEN -C playground
              pm2 serve playground 3000
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master